### 로그아웃
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/users/logout
### 관리자 회원가입
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/users
Content-Type: application/json

{
  "name" : "tester2",
  "email" : "test2@example.com",
  "password" : "tester123^^",
  "role" : "admin"
}

### 유저 회원가입
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/users
Content-Type: application/json

{
  "name" : "tester",
  "email" : "test@example.com",
  "password" : "tester123^^",
  "role" : "user"
}
### 관리자 로그인
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/users/login
Content-Type: application/json

{
  "name" : "tester2",
  "email" : "test2@example.com",
  "password" : "tester123^^",
  "role" : "admin"
}
### 워크스페이스 생성
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/workspaces/admin
Content-Type: application/json

{
  "userId" : 1,
  "name" : "testworkspace",
  "description" : "test~~~"
}
### 보드 생성
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/boards/1
Content-Type: application/json

{
  "userId" : 1,
  "title" : "board",
  "color" : "red"
}
### 멤버 초대
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/members/test@example.com
Content-Type: application/json

{
  "memberRole" : "BOARD",
  "workspaceId" : 1,
  "userId" : 2
}
### 유저 로그인
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/users/login
Content-Type: application/json

{
  "name" : "tester",
  "email" : "test@example.com",
  "password" : "tester123^^",
  "role" : "user"
}

### 리스트 생성 (3번)
POST  http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/lists/1
Content-Type: application/json

{
  "title" : "list"
}

### 리스트 수정
PATCH http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/lists/1/1
Content-Type: application/json

{
  "title" : "change order 1 to 3",
  "order": 3
}

### 리스트 생성 (1번)
POST  http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/lists/1
Content-Type: application/json

{
  "title" : "list"
}


### 리스트 삭제 (아이디 1번)
DELETE http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/lists/1


### 카드 생성 3번
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/workspaces/1/boards/1/lists/2/cards
Content-Type: application/json

{
  "title" : "Card1",
  "content" : "content1",
  "dueDate" : "2025-01-10T12:00:00"
}
### 카드 생성 3번
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/workspaces/1/boards/1/lists/2/cards
Content-Type: application/json

{
  "title" : "Card2",
  "content" : "coding",
  "dueDate" : "2025-01-10T12:00:00"
}

### 카드 리스트간 이동 (2번 -> 3번)
PATCH http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/workspaces/1/lists/2/cards/1?processListId = 3

### 카드 검색
GET http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards
Content-Type: application/json

{
  "title": "Ca",
  "content": "cod",
  "pageNumber": 1,
  "pageSize": 5
}

### 댓글 작성 3번
POST http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards/2/comments
Content-Type: application/json

{
  "content" : "comment"
}

### 카드 전체 검색
GET http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards
Content-Type: application/json

{
  "pageNumber": 1,
  "pageSize": 5
}

### 댓글을 작성한 2번 카드 상세 조회
GET http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards/2


### 보드 단건 조회
GET http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/boards/1

### 파일 업로드
POST /api/v1/workspaces/1/cards/2 HTTP/1.1
Host: ec2-52-87-160-81.compute-1.amazonaws.com:8080
Cookie: JSESSIONID=2F28CBFE87C8EC91E9CBA9BA32CAACF6
Content-Length: 207
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="picture.jpg"
Content-Type: image/jpeg

< C:/Users/thdwj/Desktop/picture.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### 파일 조회
GET http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards/2/files

### 파일 삭제
DELETE http://ec2-52-87-160-81.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards/2/files/1