### 로그아웃
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/users/logout
### 관리자 회원가입
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/users
Content-Type: application/json

{
  "name" : "tester2",
  "email" : "test2@example.com",
  "password" : "tester123^^",
  "role" : "admin"
}

### 유저 회원가입
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/users
Content-Type: application/json

{
  "name" : "tester",
  "email" : "test@example.com",
  "password" : "tester123^^",
  "role" : "user"
}
### 관리자 로그인
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/users/login
Content-Type: application/json

{
  "name" : "tester2",
  "email" : "test2@example.com",
  "password" : "tester123^^",
  "role" : "admin"
}
### 워크스페이스 생성
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/workspaces/admin
Content-Type: application/json

{
  "userId" : 1,
  "name" : "testworkspace",
  "description" : "test~~~"
}

### 멤버 초대
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/members/test@example.com
Content-Type: application/json

{
  "memberRole" : "BOARD",
  "workspaceId" : 1,
  "userId" : 2
}
### 유저 로그인
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/users/login
Content-Type: application/json

{
"name" : "tester",
"email" : "test@example.com",
"password" : "tester123^^",
"role" : "user"
}

### 보드 생성

POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/api/v1/boards/1
Content-Type: application/json

{
  "title" : "board1",
  "color" : "red"
}

### 리스트 생성
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/api/v1/lists/1
Content-Type: application/json

{
  "title" : "list1"
}

### 리스트 삭제
DELETE http://


### 카드 생성
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/api/v1/workspaces/1/boards/1/lists/1/cards
Content-Type: application/json

{
  "title" : "Card",
  "content" : "card",
  "dueDate" : "2025-01-10T12:00:00"
}
### 카드 검색
GET http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards
Content-Type: application/json

{
  "pageNumber" : 1,
  "pageSize" : 10
}


### 파일 업로드
POST http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards/1 HTTP/1.1
Cookie: JSESSIONID=2F28CBFE87C8EC91E9CBA9BA32CAACF6
Content-Length: 207
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="picture.jpg"
Content-Type: image/jpeg

< C:/Users/thdwj/Desktop/picture.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW---



### 파일 조회
GET http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards/1/files
Content-Type: application/json

### 파일 삭제
DELETE http://ec2-44-211-141-234.compute-1.amazonaws.com:8080/api/v1/workspaces/1/cards/1/files/2
Content-Type: application/json