### 로그아웃
POST http://localhost:8080/users/logout
### 관리자 회원가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "name" : "tester2",
  "email" : "test2@example.com",
  "password" : "tester123^^",
  "role" : "admin"
}

### 회원가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "name" : "tester",
  "email" : "test@example.com",
  "password" : "tester123^^",
  "role" : "user"
}
### 관리자 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "name" : "tester2",
  "email" : "test2@example.com",
  "password" : "tester123^^",
  "role" : "admin"
}
### 워크스페이스 생성
POST http://localhost:8080/workspaces/admin
Content-Type: application/json

{
  "userId" : 1,
  "name" : "testworkspace",
  "description" : "test~~~"
}

### 멤버 초대
POST http://localhost:8080/members/test@example.com
Content-Type: application/json

{
  "memberRole" : "BOARD",
  "workspaceId" : 1,
  "userId" : 2
}
### 유저 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
"name" : "tester",
"email" : "test@example.com",
"password" : "tester123^^",
"role" : "user"
}




### 카드 생성
POST http://localhost:8080/api/v1/workspaces/1/boards/1/lists/1/cards
Content-Type: application/json

{
  "title" : "Card",
  "content" : "card",
  "dueDate" : "2025-01-10T12:00:00"
}
### 카드 검색
GET /api/v1/workspaces/1/cards?boardId=null HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cookie: JSESSIONID=2F28CBFE87C8EC91E9CBA9BA32CAACF6
Content-Length: 10

{

}
### 파일 업로드
POST /api/v1/workspaces/1/cards/1 HTTP/1.1
Host: localhost:8080
Cookie: JSESSIONID=2F28CBFE87C8EC91E9CBA9BA32CAACF6
Content-Length: 207
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="picture.jpg"
Content-Type: image/jpeg

< C:/Users/thdwj/Desktop/picture.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW---

### 파일 조회
GET http://localhost:8080/api/v1/workspaces/1/cards/1/files
Content-Type: application/json

### 파일 삭제
DELETE http://localhost:8080/api/v1/workspaces/1/cards/1/files/1
Content-Type: application/json